//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetAllCountriesResponse> GetAllCountriesAsync(ServiceReference1.GetAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetCountryByCodeResponse> GetCountryByCodeAsync(ServiceReference1.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetCityByNameResponse> GetCityByNameAsync(ServiceReference1.GetCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetCitiesByCountryResponse> GetCitiesByCountryAsync(ServiceReference1.GetCitiesByCountryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountries", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetAllCountriesRequestBody Body;
        
        public GetAllCountriesRequest()
        {
        }
        
        public GetAllCountriesRequest(ServiceReference1.GetAllCountriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCountriesRequestBody
    {
        
        public GetAllCountriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCountriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetAllCountriesResponseBody Body;
        
        public GetAllCountriesResponse()
        {
        }
        
        public GetAllCountriesResponse(ServiceReference1.GetAllCountriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCountriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString GetAllCountriesResult;
        
        public GetAllCountriesResponseBody()
        {
        }
        
        public GetAllCountriesResponseBody(ServiceReference1.ArrayOfString GetAllCountriesResult)
        {
            this.GetAllCountriesResult = GetAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest()
        {
        }
        
        public GetCountryByCodeRequest(ServiceReference1.GetCountryByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCountryByCodeRequestBody()
        {
        }
        
        public GetCountryByCodeRequestBody(string countryCode)
        {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse()
        {
        }
        
        public GetCountryByCodeResponse(ServiceReference1.GetCountryByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody()
        {
        }
        
        public GetCountryByCodeResponseBody(string GetCountryByCodeResult)
        {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByName", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCityByNameRequestBody Body;
        
        public GetCityByNameRequest()
        {
        }
        
        public GetCityByNameRequest(ServiceReference1.GetCityByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityName;
        
        public GetCityByNameRequestBody()
        {
        }
        
        public GetCityByNameRequestBody(string cityName)
        {
            this.cityName = cityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCityByNameResponseBody Body;
        
        public GetCityByNameResponse()
        {
        }
        
        public GetCityByNameResponse(ServiceReference1.GetCityByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCityByNameResult;
        
        public GetCityByNameResponseBody()
        {
        }
        
        public GetCityByNameResponseBody(string GetCityByNameResult)
        {
            this.GetCityByNameResult = GetCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountry", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCitiesByCountryRequestBody Body;
        
        public GetCitiesByCountryRequest()
        {
        }
        
        public GetCitiesByCountryRequest(ServiceReference1.GetCitiesByCountryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCitiesByCountryRequestBody()
        {
        }
        
        public GetCitiesByCountryRequestBody(string countryCode)
        {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetCitiesByCountryResponseBody Body;
        
        public GetCitiesByCountryResponse()
        {
        }
        
        public GetCitiesByCountryResponse(ServiceReference1.GetCitiesByCountryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.ArrayOfString GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponseBody()
        {
        }
        
        public GetCitiesByCountryResponseBody(ServiceReference1.ArrayOfString GetCitiesByCountryResult)
        {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebService1SoapChannel : ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebService1Soap>, ServiceReference1.WebService1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAllCountriesResponse> ServiceReference1.WebService1Soap.GetAllCountriesAsync(ServiceReference1.GetAllCountriesRequest request)
        {
            return base.Channel.GetAllCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAllCountriesResponse> GetAllCountriesAsync()
        {
            ServiceReference1.GetAllCountriesRequest inValue = new ServiceReference1.GetAllCountriesRequest();
            inValue.Body = new ServiceReference1.GetAllCountriesRequestBody();
            return ((ServiceReference1.WebService1Soap)(this)).GetAllCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetCountryByCodeResponse> ServiceReference1.WebService1Soap.GetCountryByCodeAsync(ServiceReference1.GetCountryByCodeRequest request)
        {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCountryByCodeResponse> GetCountryByCodeAsync(string countryCode)
        {
            ServiceReference1.GetCountryByCodeRequest inValue = new ServiceReference1.GetCountryByCodeRequest();
            inValue.Body = new ServiceReference1.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((ServiceReference1.WebService1Soap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetCityByNameResponse> ServiceReference1.WebService1Soap.GetCityByNameAsync(ServiceReference1.GetCityByNameRequest request)
        {
            return base.Channel.GetCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCityByNameResponse> GetCityByNameAsync(string cityName)
        {
            ServiceReference1.GetCityByNameRequest inValue = new ServiceReference1.GetCityByNameRequest();
            inValue.Body = new ServiceReference1.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            return ((ServiceReference1.WebService1Soap)(this)).GetCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetCitiesByCountryResponse> ServiceReference1.WebService1Soap.GetCitiesByCountryAsync(ServiceReference1.GetCitiesByCountryRequest request)
        {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetCitiesByCountryResponse> GetCitiesByCountryAsync(string countryCode)
        {
            ServiceReference1.GetCitiesByCountryRequest inValue = new ServiceReference1.GetCitiesByCountryRequest();
            inValue.Body = new ServiceReference1.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((ServiceReference1.WebService1Soap)(this)).GetCitiesByCountryAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44346/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44346/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
